name: AutoCodeGen
on:
  issues:
    types: [labeled]

jobs:
  generate_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: foo
        uses: RO1303/AutoCoder@main
        with:
          who-to-greet: 'Rona the Octocat'
          github_token: $\{{ secrets.GITHUB_TOKEN }}
          repository: $GITHUB_REPOSITORY
          issue_number: ${{ github.event.issue.number }}
          script_path: RO1303/AutoCoder/scripts/script.sh
          openai_api_key: $\{{ secrets.OPENAI_API_KEY }}
          issue_label: 'autocoder'

      - run: echo ${{ steps.foo.outputs.pull_request_url }}
        shell: bash
