name: AutoCodeGen
on:
  issues:
    types: [labeled]

jobs:
  generate_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: foo
        uses: RO1303/AutoCoder@main
        with:
          GITHUB_TOKEN: $\{{ secrets.GITHUB_TOKEN }}
          REPOSITORY: $GITHUB_REPOSITORY
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          SCRIPT_PATH: RO1303/AutoCoder/scripts
          OPENAI_API_KEY: $\{{ secrets.OPENAI_API_KEY }}
          LABEL: 'autocoder'

      - run: echo ${{ steps.foo.outputs.pull_request_url }}
        shell: bash


# "GITHUB_TOKEN", "REPOSITORY", "ISSUE_NUMBER", "OPENAI_API_KEY", "SCRIPT_PATH", "LABEL"
