name: AutoCodeGen
on:
  issues:
    types: [labeled]

jobs:
  generate_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: foo
        uses: RO1303/AutoCoder@main
        with:
          who-to-greet: 'Rona the Octocat'
      - run: echo ${{ steps.foo.outputs.pull_request_url }}
        shell: bash
