
## Using the AutoCoder Composite Action
## To use this action, set up a `.github/workflows/main.yml` file in your repository like that below
name: AutoCodeGen
on:
  issues:
    types: [labeled]

jobs:
  generate_code:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello from test-action repository workflow main.yml"
      - name: Checkout
        uses: actions/checkout@main
      - name: AutoCoder Composite Action
        uses: RO1303/AutoCoder@main
        with:
          github_token: $\{{ secrets.GITHUB_TOKEN }}
          repository: $GITHUB_REPOSITORY
          issue_number: ${{ github.event.issue.number }}
          script_path: RO1303/AutoCoder/scripts/script.sh
          openai_api_key: $\{{ secrets.OPENAI_API_KEY }}
          issue_label: 'autocoder'

  print_output:
    runs-on: ubuntu-latest
    needs: generate_code
    steps:
      - run: echo ${{ needs.generate_code.outputs.pull_request_url.value }}

