on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: RO1303/AutoCoder@main
        with:
          who-to-greet: 'Rona the Octocat'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
      - run: echo ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: echo ${{ steps.foo.outputs.pull_request_url }}
        shell: bash
